### ISSUE TITLE
Add html template for item-box

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#11]
It would be very helpful to have an html-template. Div container that should be the template: 
`<div class="grid-content item" ng-repeat="item in Response.hits.hits">` 

The `ng-repeat="item in Response.hits.hits"` should be variable so that I can use this template to create single items for the item-display function (in a modal-window) for saved items.

Related: [https://docs.angularjs.org/guide/templates](https://docs.angularjs.org/guide/templates)

**Comment by thirdy** [comment]
done by @Eruyome
