### ISSUE TITLE
Add CSS-Classes to mods and item names to color them

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#14]
Mods should have classes to color them (life, resists) and item names should have different colors depending on rarity.

**Comment by Dominik-O22** [comment]
depending on Rarity? not on type?

**Comment by Eruyome** [comment]
Why on type? Magic Item = blue, Rare Item = yellow, Unique = brownish. That's how it's in the game and on poe.trade

**Comment by Dominik-O22** [comment]
so you want for example life on items differently colored based on rarity of the item? ups i didnt read that you wanted to read the item name itself the recolor

**Comment by kyri0** [comment]
Fire res: Red
Cold res: Blue
Light res: Yellow
Stuff like that

**Comment by Eruyome** [comment]
Yes. Like that.

**Comment by thirdy** [comment]
Did this with the item name. the solution for this should be the same huh?

On Fri, Mar 4, 2016 at 8:52 AM, Eruyome notifications@github.com wrote:

> Yes. Like that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/14#issuecomment-192039760
> .

## 

## 

http://sites.google.com/site/thirdyderivera/
