### ISSUE TITLE
Update screenshot for readme

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#15]

**Comment by thirdy** [comment]
Done

![capture](https://cloud.githubusercontent.com/assets/75921/14044084/09984126-f2c7-11e5-8796-7986b1aeef17.PNG)

**Comment by thirdy** [comment]
![capture](https://cloud.githubusercontent.com/assets/75921/14044114/7a99ae46-f2c7-11e5-8ef2-f902427624fe.PNG)
