### ISSUE TITLE
sort by currency

### ISSUE THREAD

**Issue by Moksu** [exiletrade/exiletrade#18]
sort searched items by currency.

**Comment by thirdy** [comment]
done by sorting by cheapest first, note that it cannot switch between sort asc vs desc. Just asc which is cheapest.

pls test. cc: @kyri0

**Comment by Dominik-O22** [comment]
seems to work only problem is that items without a buyout have a chaosequiv of 0 means they are always on top of the search

**Comment by Moksu** [comment]
Not possible to add Search Input what will ignore items with no buyout?

**Comment by Dominik-O22** [comment]
yes it is possible to add bo as a search term to only get items with a buyout

**Comment by thirdy** [comment]
fixed
