### ISSUE TITLE
Make a list of searches for reference

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#19]
Make a list of searches. Build specific ones like searching for jewels. And common searches like finding a decent ring.
This is for reference to see what exiletrade is capable of (just like those junk I put in Durian/manual by default).

Wanna add this btw: You can even search multiple things in one go:

```
(tabula 20c) OR (goldrim 10c)
```

can be useful for shopping for good leveling gear or very high-end items where you'd only expect very few results.

another:
`unique (ring OR amulet) (iiq OR iir)`

**Comment by thirdy** [comment]
would be great if we have these as default saved searches

**Comment by Dominik-O22** [comment]
I would say we have this now in form of the sample searches
