### ISSUE TITLE
Fix weapon stat display (dps, aps etc)

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#2]
The tables displaying those stats work for armour, partly for shields (no block), gems but not for weapons. I'ts simply dumb what I did there because I didn't know the JSON for weapons at the time and thought all mods were available in modsPseudo. The weapons probably need the 'forgottenMods' treatment. There's no styling involved in fixing this. Only anguar/JS. 

Could someone fix this for me? (css-class "item-stats" to find it faster)

**Comment by kyri0** [comment]
Just to name them all:

*DPS
*EDPS
*PDPS
*APS
*Crit Chance
*Phys dmg range
*Ele dmg range

**Comment by ayan4m1** [comment]
- properties.Weapon.Fire DPS
- properties.Weapon.Lightning DPS
- properties.Weapon.Physical DPS
- properties.Weapon.Total DPS
- properties.Weapon.Cold DPS
- properties.Weapon.Elemental DPS
- properties.Weapon.Chaos DPS
- properties.Weapon.Attacks per Second
- propertiesPseudo.Armour.estimatedQ20.Armour
- propertiesPseudo.Armour.estimatedQ20.Energy Shield
- propertiesPseudo.Armour.estimatedQ20.Evasion Rating
- propertiesPseudo.Weapon.estimatedQ20.Physical DPS

**Comment by thirdy** [comment]
I've added the display for:

```
properties.Weapon.Fire DPS
properties.Weapon.Lightning DPS
properties.Weapon.Physical DPS
properties.Weapon.Total DPS
properties.Weapon.Cold DPS
properties.Weapon.Elemental DPS
properties.Weapon.Chaos DPS
properties.Weapon.Attacks per Second
```

deployed to live.

would appreciate if tester can point out what else is missing.

**Comment by thirdy** [comment]
@kyri0 , can you test it out?

**Comment by Dominik-O22** [comment]
would be great to haev tooltips for them and being able to sort by them
