### ISSUE TITLE
Search for implicits, item name and talismans (literal name search)

### ISSUE THREAD

**Issue by kyri0** [exiletrade/exiletrade#22]
Basically all amounts to the same problem.

I haven't found the query for any of the talismans on the exile tools mapping page, so we need another way to look for them, either by the name or by the implicit.

Besides, it's nice to have the hability to search by an items name as we had with name="stuff". Or `literal name`to have a fancy name.

**Comment by Dominik-O22** [comment]
as the bad user input correction takes all unrecognized inputs as names, i consider this issue resolved
