### ISSUE TITLE
Options should be saved on reload of the site

### ISSUE THREAD

**Issue by Xebtria** [exiletrade/exiletrade#29]
Most importantly the league. I do not want to make 4 clicks every time I reload the site to set my league. but all options should be saved.

Also, would suggest to make Perandus SC the default (like it is/will be in the game as well when you create a new character).

I think that is a blocker, while the site works even without, it is extremely annoying.

**Comment by Eruyome** [comment]
As far as I know these options are still placeholders anyway and not used.
