### ISSUE TITLE
define sort condition via search bar 

### ISSUE THREAD

**Issue by Dominik-O22** [exiletrade/exiletrade#34]
It would be really useful, in cases where the user already knows after which criteria, which is not the standard, to sort the result as it would could down on the amount of time it takes the user from opening the page till finding the item he wants

**Comment by thirdy** [comment]
we can probably add a special condition into the blackmarket engine where
if the user input contains a \bsort.+\b then we should grab that sort
search term and override the current sort

On Sun, Mar 6, 2016 at 9:26 AM, Dom notifications@github.com wrote:

> It would be really useful, in cases where the user already knows after
> which criteria, which is not the standard, to sort the result as it would
> could down on the amount of time it takes the user from opening the page
> till finding the item he wants
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/34.

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by thirdy** [comment]
related to #82

I think we can easily allow multi-ordering. The hard work is to handle it via search terms. Implementing it via url would be easy as documented [here](https://docs.angularjs.org/api/ng/service/$location). But that would clutter the url.

Therefore sorting should be done via search terms.

ExileTools/Elastic is actually expecting an array of sorting options:

```
        function doElasticSearch(searchQuery, _from, _size, sortKey, sortOrder) {
            var esBody = buildEsBody(searchQuery);
            var esPayload = {
                index: 'index',
                sort: [sortKey + ':' + sortOrder],
                from: _from,
                size: _size,
                body: esBody
            };
            $scope.elasticJsonRequest = angular.toJson(esPayload, true);
            //debugOutput("Gonna run elastic: " + $scope.elasticJsonRequest, 'trace');
            return es.search(esPayload);
        }
```

**Comment by thirdy** [comment]
Done, sample search:

http://exiletra.de/?q=Doryani%27sCatalyst%20inceledmgdesc%20boasc

idea here is that you can use [most] search term to specify a sorting but you append it with "asc" (ascending) or "desc" (descending)

for example `Varunastra pdpsDesc`, here im using pdps search term and added "desc" to it.
this will be parsed as:

```
  "sort": [
    "propertiesPseudo.Weapon.estimatedQ20.Physical DPS:desc"
  ],
```

with `Varunastra pdpsDesc boAsc`, show me the items in order highest pdps then order them by price

```
   "sort": [
    "propertiesPseudo.Weapon.estimatedQ20.Physical DPS:desc",
    "shop.chaosEquiv:asc"
  ],
```
