### ISSUE TITLE
Add image-art to search terms

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#46]
I think we can do a very cool way of finding items by art by clicking on art.

For example, i wanna buy a "Heavy Strike". I would access a categorized ui where i can easily find and click this:

![hs](http://webcdn.pathofexile.com/image/Art/2DItems/Gems/HeavyStrike.png)

this would add the search term `heavystrike` into the search input.

This would probably realize also my idea of a better way of viewing uniques:

https://www.reddit.com/r/pathofexiledev/comments/3w1ccl/idea_a_more_immersive_uniques_viewer/

**Comment by Dominik-O22** [comment]
so you think dropdown menus are slow becuase you haev to confirm your selection but finding ksill gems by item art is faster than typing?
