### ISSUE TITLE
UI proposal: make saved searches show be default

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#47]
would be so so nice if we can have the saved searches shown always like in Durian:

![durian](https://cloud.githubusercontent.com/assets/75921/12061705/40575b44-afc8-11e5-8fd2-e4e2988648f7.PNG)

**Comment by Eruyome** [comment]
Would advise against it. Takes up too much space.

**Comment by thirdy** [comment]
ok, I'd settle for a button that would show it up using:

http://foundation.zurb.com/apps/docs/#!/off-canvas

This button however is persistent; meaning it's state will be saved into
the browser. The next time the user visits the site, state is preserved.
User is free to hide it.
