### ISSUE TITLE
Add Paging

### ISSUE THREAD

**Issue by Dominik-O22** [exiletrade/exiletrade#52]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html
docu for script implementation,

**Comment by bolte-17** [comment]
Or infinite scroll, using the same mechanisms.

**Comment by thirdy** [comment]
infinite scroll seems easy with this:

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-2-2.html#api-search-2-2

**Comment by thirdy** [comment]
implemented scrolling
