### ISSUE TITLE
Register to omnibox automatically

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#68]
http://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site

**Comment by Dominik-O22** [comment]
this would be great

**Comment by thirdy** [comment]
done, it's now live

https://www.reddit.com/r/pathofexile/comments/4de1h1/filter_out_those_wtb_only_items_with_exiletrade/
