### ISSUE TITLE
forced offline for autosearch

### ISSUE THREAD

**Issue by Dominik-O22** [exiletrade/exiletrade#71]
We need to be able to disable the online only display for the autosearch, as it can happen that someone, who is considered offline, lists an item that would get picked up by the autosearch, causing the scenario where the user gets notified of a new item, but is unable to see it

**Comment by thirdy** [comment]
I thought the auto search doesnt have the online only filter - at least
that what I think I implement initially.
havent had a look at dev site

On Tue, Mar 29, 2016 at 4:02 AM, Dom notifications@github.com wrote:

> We need to be able to disable the online only display for the autosearch,
> as it can happen that someone, who is considered offline, lists an item
> that would get picked up by the autosearch, causing the scenario where the
> user gets notified of a new item, but is unable to see it
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/71

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by Dominik-O22** [comment]
well this is more about the current display solution, where we simply use it it as a timestamped search, the search itself does not concern about the seller
