### ISSUE TITLE
Decide on design for option checkboxes

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#72]
On zocke1r's suggestion I changed the checkboxes in the option panel. I'm not 100% for this new design but I made it so that we only have to add/remove one css-class to switch between the two designs.  

`<li class="showLabelOnInput">` 

This class has to be assigned to the enclosing html-element to have the new design. 
Here's a quick comparison between the designs.

![preview](https://cloud.githubusercontent.com/assets/16058242/14091026/0287f998-f53e-11e5-91bb-f909d6bc6bcc.png)

**Comment by kyri0** [comment]
I'm thinking they're both visually nice, but i'd go with zockers suggestion an keep the second one, but i'm also thinking it may be confusing for someone that doesn't know what all the buttons do.

**Comment by thirdy** [comment]
I like the one on the right.

More importantly these should be accessible by keyboard shortcuts. Options
menu can be opened via open via ctrl+o, then nativate up/down arrow, enter
key for toggle/edit., then esc to close the menu. No need for save button,
any change should be saved immediately.

On Tue, Mar 29, 2016 at 11:40 PM, kyri0 notifications@github.com wrote:

> I'm thinking they're both visually nice, but i'd go with zockers
> suggestion an keep the second one, but i'm also thinking it may be
> confusing for someone that doesn't know what all the buttons do.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/72#issuecomment-202963964

## 

## 

http://sites.google.com/site/thirdyderivera/

**Comment by kyri0** [comment]
I assume this is already decided, so i'll close the issue.
