### ISSUE TITLE
Autocomplete Unique items name

### ISSUE THREAD

**Issue by cristianvuolo** [exiletrade/exiletrade#77]
it would be very wise to add an autocomplete system the name of unique items as there is in poe.trade

![PoeTrade auto-complete](http://i.imgur.com/WpEiYHJ.png)

**Comment by Dominik-O22** [comment]
we are currently working on an autocomplete solution for every term in our term sheets, so this is coming really soon, we only have to finish a few things till we can release it

**Comment by thirdy** [comment]
deployed to live.
doesn't have fuzzy search but let's have that on another ticket

**Comment by thirdy** [comment]
also, it would be nice it typeahead.js was used. But I went with:
http://hakib.github.io/MassAutocomplete/
as it supports multi value autocomplete w/c we need as we have multi term input.

while typeahead have that nice complete-on-tab

**Comment by thirdy** [comment]
Screenshot upload for forum post

![capture](https://cloud.githubusercontent.com/assets/75921/14409790/d5b8aab8-ff4f-11e5-9536-1ae40cc20c2e.PNG)
