### ISSUE TITLE
Whisper options

### ISSUE THREAD

**Issue by Manabarb** [exiletrade/exiletrade#78]
Can we have a whisper and autowhisper options instead of just an autowhisper that is labeled as whisper? Not everyone wants to start the conversation the same way when they buy an item, but we could have both the @user and the @user automsg for those who chose to use it, but label them differently, maybe label them as "simple whisper/fetch username" and "formal whisper/direct item request"

**Comment by Eruyome** [comment]
Do we really have to add a button for this? You could just doubleclick the IGN and ctrl+c. Typing the @ ingame isn't much work either.

Doesn't this just add unnecessary clutter for almost no convenience at all?

**Comment by thirdy** [comment]
added a link to the ign
