### ISSUE TITLE
enable www.exiletra.de

### ISSUE THREAD

**Issue by thirdy** [exiletrade/exiletrade#81]
already go http://exiletra.de working, need to enable that www too

**Comment by kyri0** [comment]
I assume this was already enabled as I can type www.exiletra.de on the address bar and it works (tested on multiple browsers.

**Comment by thirdy** [comment]
Oh, didn't know that haha

On Sun, Apr 17, 2016 at 7:23 AM, kyri0 notifications@github.com wrote:

> Closed #81 https://github.com/exiletrade/exiletrade/issues/81.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/exiletrade/exiletrade/issues/81#event-630124293

## 

## 

http://sites.google.com/site/thirdyderivera/
