### ISSUE TITLE
Quality calculations for weapons are done incorrectly.

### ISSUE THREAD

**Issue by Riizade** [exiletrade/exiletrade#94]
From the quality page on the wiki (http://pathofexile.gamepedia.com/Quality):

> Quality on weapons grant increased Physical Damage equal to a number of quality that stacks additively with increased Physical Damage modifier on the weapon.

Here is a screenshot on the live site.

![marohibug](https://cloud.githubusercontent.com/assets/1762469/15802623/852e3ac4-2a86-11e6-98d9-5a754af1d0c4.JPG)

The only attribute that modifies DPS on Marohi Erqi is the increased physical damage. Both weapons have the same stats in this regard, which would put their base DPS at the same value (362 pDPS).
The Marohi Erqi on the right already has 20 quality, and the DPS is calculated by the game at
`avgdmg * (quality+increasedphysdmg+100%) * attackspersecond`
`= 113.5 * (20%+223%+100%) * 0.99 = 385`

The Marohi Erqi on the left has all the same stats with respect to DPS except for the quality, and is calculated by ExileTrade as
`avgdmg * (increasedphysdmg+100%) * (quality+100%) * attackspersecond`
`= 113.5 * (223%+100%) * (20%+100%) * 0.99 = 435ish`

We can instead get the correct DPS value from the current DPS value by using
`dps * (quality/(100%+increasedphysdmg)`
`= 362 * (100% + 20%/(100%+223%)) = 384.4`

EDIT: Quote and screenshot taken from the wiki and exiletra.de respectively on June 4th, 2016, 7:12PM EDT

**Comment by kyri0** [comment]
Thanks for noticing it. The DPS calculations aren't actually done by ExileTrade, it only queries Exile Tools index. The property that's being miss calculated is "propertiesPseudo.Weapon.estimatedQ20.Physical DPS". We'll let trackpete know.

**Comment by Riizade** [comment]
My bad.

I did a quick search using the GitHub search tool to see if I could find where the calculation happened in this repo, and that explains why I didn't find it. :P

**Comment by kyri0** [comment]
Posted it there, in case you wanna follow it:
https://github.com/trackpete/exiletools-indexer/issues/146

**Comment by pete-wn** [comment]
I've fixed this on the indexer side - during some code re-organization, I foolishly moved the Q20 calculation section to take place before mods were determined...  so everything was being calculated as if it had no mods. Very stupid.

I'll be deploying to production and starting a re-index from scratch sometime today.

**Comment by kyri0** [comment]
Thanks for the quick fix ;)

**Comment by pete-wn** [comment]
Re-index is complete now so this should be all good - let me know if you encounter any further problems like this!

**Comment by kyri0** [comment]
Yeah, it's fixed! Keep up the good work :)
