### ISSUE TITLE
fromPerandusCoin does not work

### ISSUE THREAD

**Issue by jmis** [exiletrade/exiletrade#97]
The query "ReachoftheCouncil fromPerandus" returns no results.  Other currency related queries work correctly such as "ReachoftheCouncil fromEx".

**Comment by thirdy** [comment]
There's an extra 's' on the definition of perandus coin. Fix is just to correct it from the google spreadsheet and do a deploy. Soon.

![capture](https://cloud.githubusercontent.com/assets/75921/16665594/cb5e7cf8-44b6-11e6-9bf9-b331f4e33476.PNG)

![capture2](https://cloud.githubusercontent.com/assets/75921/16665593/cb5da878-44b6-11e6-9243-1f9d9da99496.PNG)

Thanks for reporting

**Comment by thirdy** [comment]
deployed fix:

http://exiletra.de/?q=fromPerandusCoin

**Comment by jmis** [comment]
Looks like it works!  Thank you.
