### ISSUE TITLE
Typo in "adds <Type> Damage to Attacks" search terms

### ISSUE THREAD

**Issue by MordecaiMalignatus** [exiletrade/exiletrade#98]
![image](https://cloud.githubusercontent.com/assets/781633/16926139/cda54c5c-4d27-11e6-9983-d0ddfed27b67.png)

Missing a T respectively. Bugged me, sorry if it's too small to warrant a ticket. :)

**Comment by kyri0** [comment]
Yeah, thanks, fixed it!
